In [9]:
import pandas as pd
df = pd.DataFrame({
    'fruit': ['apple', 'banana', 'apple', 'orange', 'banana', 'apple'],
    'color': ['red', 'yellow', 'green', 'orange', 'yellow', 'red']
})

In [10]:
df.groupby('fruit').size()

fruit
apple     3
banana    2
orange    1
dtype: int64

In [15]:
pd.crosstab(df["fruit"] , df["color"])

color   green  orange  red  yellow
fruit
apple       1       0    2       0
banana      0       0    0       2
orange      0       1    0       0

In [13]:
pd.pivot_table(df , index="fruit" , columns="color" , aggfunc="size" , fill_value=0)

color   green  orange  red  yellow
fruit
apple       1       0    2       0
banana      0       0    0       2
orange      0       1    0       0